JAMAI_API_KEY = "jamai_pat_7ae4705e94626c86ee6b91d31476904e66682e2cb4688353" #remember to change to your jam ai base PAT
JAMAI_PROJECT_ID = "proj_40bb85c8046507296f359434" #remember to copy your project ID
JAMAI_ACTION_TABLE_ID = "Contract_Auditor_Full"
JAMAI_CHATBOT_ACTION_TABLE_ID = "Chatbot"
