JAMAI_API_KEY = "YOUR_API_KEY" #remember to change to your jam ai base PAT
JAMAI_PROJECT_ID = "YOUR_PROJECT_ID" #remember to copy your project ID
JAMAI_ACTION_TABLE_ID = "Contract_Auditor_Full"
JAMAI_CHATBOT_ACTION_TABLE_ID = "Chatbot"